server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/laptopShop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: vuhoangduy
    password: Vhd28704
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
  security :
    oauth2:
      client:
        registration:
          google:
            client-id: 665234947979-et587m5nie7rffgp1ljok43cfs5ijhs1.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
    jwt:
      secret: your_secret_key
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
